<?php
namespace WodorNet\MotoTripBundle\Twig\Extension;


require_once '/home/wodor/wrk/www/motowypady/src/WodorNet/MotoTripBundle/Twig/Extension/MotoTripExtension.php';

/**
 * Test class for MotoTripExtension.
 * Generated by PHPUnit on 2012-01-16 at 19:52:20.
 */
class MotoTripExtensionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MotoTripExtension
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MotoTripExtension;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetFilters().
     */
    public function testGetFilters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testIntldate().
     */
    public function testIntldate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }



    public function intervalsProvider() {

        // we always create interval by \DateTime::diff()
        // because of bug
        // https://bugs.php.net/bug.php?id=60774.
        $now = new \DateTime();
        $twoDaysBefore = new \DateTime('-2 days');
        $twoHoursBefore = new \DateTime('-2 hours');

        return array(
           array( "2 h", $twoHoursBefore->diff($now)),
           array( "2 d", $twoDaysBefore->diff($now)),
        );
    }

    /**
     * @dataProvider  intervalsProvider
     */
    public function testIntlinterval($string, $interval)
    {
        $this->assertEquals($string, $this->object->intlinterval($interval));
    }

    /**
     * @todo Implement testCrop().
     */
    public function testCrop()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
