imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true


mink:
    base_url:   http://motowypady.tyr/app_test.php
    show_cmd:             google-chrome %s
    sahi:       ~
    browser_name:  chrome
    default_session:     sahi


doctrine:
    dbal:
        connections:
             default:
                driver:   pdo_sqlite
                path:     %kernel.cache_dir%/test.db
    orm:
        auto_generate_proxy_classes: true
        auto_mapping: true