<?php

namespace WodorNet\MotoTripBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoadTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoadTypeRepository extends EntityRepository
{
}